# Generated by Django 5.2.1 on 2025-06-13 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automodeler', '0005_alter_dataset_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessedDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('csv_file', models.FileField(upload_to='preprocessed_datasets/')),
                ('original_dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='automodeler.dataset')),
            ],
        ),
    ]
