# Generated by Django 5.2.1 on 2025-06-19 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automodeler', '0006_preprocesseddataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_file', models.FileField(upload_to='models/')),
                ('model_method', models.CharField(choices=[('LogisticRegression', 'Logistic Regression'), ('RandomForestClassifier', 'Random Forest Classifier'), ('GradientBoostingClassifier', 'Gradient Boosting Classifier'), ('SVC', 'SVC'), ('LinearRegression', 'Linear Regression'), ('RandomForestRegressor', 'Random Forest Regressor'), ('GradientBoostingRegressor', 'Gradient Boosting Regressor'), ('SVR', 'SVR')], max_length=30)),
                ('model_type', models.CharField(choices=[('regression', 'Regression'), ('classification', 'Classification')], max_length=15)),
                ('original_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automodeler.dataset')),
            ],
        ),
    ]
