# Generated by Django 5.2.1 on 2025-06-17 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automodeler', '0006_preprocesseddataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainTestDataFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('train', 'Train'), ('test', 'Test')], max_length=10)),
                ('axis', models.CharField(max_length=1)),
                ('tt_ds_file', models.FileField(upload_to='traintest_dataframes/')),
                ('preprocessed_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automodeler.preprocesseddataset')),
            ],
        ),
    ]
