# Generated by Django 5.2.1 on 2025-06-25 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automodeler', '0007_datasetmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TunedDatasetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_file', models.FileField(upload_to='models/')),
                ('model_method', models.CharField(choices=[('LogisticRegression', 'Logistic Regression'), ('RandomForestClassifier', 'Random Forest Classifier'), ('GradientBoostingClassifier', 'Gradient Boosting Classifier'), ('SVC', 'SVC'), ('LinearRegression', 'Linear Regression'), ('RandomForestRegressor', 'Random Forest Regressor'), ('GradientBoostingRegressor', 'Gradient Boosting Regressor'), ('SVR', 'SVR')], max_length=30)),
                ('model_type', models.CharField(choices=[('regression', 'Regression'), ('classification', 'Classification')], max_length=15)),
                ('original_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automodeler.dataset')),
                ('untuned_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='automodeler.datasetmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
