# Generated by Django 5.2.1 on 2025-07-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automodeler', '0015_dataset_excluded_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocesseddataset',
            name='selected_models',
            field=models.JSONField(default=list, null=True),
        ),
    ]
