# Generated by Django 5.2.1 on 2025-07-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automodeler', '0015_dataset_excluded_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='scores',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
