# Generated by Django 5.2.1 on 2025-07-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automodeler', '0016_datasetmodel_scores'),
        ('automodeler', '0016_preprocesseddataset_selected_models'),
    ]

    operations = [
    ]
